### ISSUE TITLE
Cannot run the package : regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by Annihil** [jaebradley/tinder-client#11]
Hi, I got this error while trying to use this npm package

```
ReferenceError: regeneratorRuntime is not defined
    at /Users/baptiste/Documents/tinder_promoter/node_modules/tinder-client/build/index.cjs.js:1:3409
    at Object.<anonymous> (/Users/baptiste/Documents/tinder_promoter/node_modules/tinder-client/build/index.cjs.js:1:4041)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
```

**Comment by jaebradley** [comment]
@Annihil taking a 👀

**Comment by jaebradley** [comment]
@Annihil #12 should resolve this issue - I had a stray `async` that I've converted to a `Promise` chain.

Let me know if you still see issues after the next `patch` update gets published to `npm`.

**Comment by Annihil** [comment]
Indeed fixed, thank you sir!
