### ISSUE TITLE
Like&Pass functions does not work

### ISSUE THREAD

**Issue by RikuHirose** [jaebradley/tinder-client#76]
### Description
Hi.Can I help?
I try to call Pass and Like  functions. But It does not work..
FacebookUserId and facebookToken are correct cuz I can call getUser function...

### code
```
require('dotenv').config({ path: __dirname + '/../.env' })
const axios = require('axios')
const facebookUserId = process.env.facebookUserId
const facebookToken = process.env.facebookToken

const {TinderClient, GENDERS, GENDER_SEARCH_OPTIONS} = require('tinder-client')
const TINDER_NUM = process.env.TINDER_NUM || 1

async function diplayCommits() {
  try{
    const tinder_client = await TinderClient.create({ facebookUserId, facebookToken })
    let recommendations = await tinder_client.getRecommendations()
    
    const user = await tinder_client.getUser(recommendations.results[0]._id)
    await tinder_client.pass(recommendations.results[0]._id)
    await tinder_client.like(recommendations.results[0]._id)
   
  }
  catch(err){
    console.log(err)
  }

}
diplayCommits()
```

### Error Message
```
{ Error: Request failed with status code 400
    at createError (/...../node_modules/axios/lib/core/createError.js:16:15)
    at settle (/...../node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/...../node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'X-Auth-Token': '......',
        'Content-Type': 'application/json',
        'User-Agent': 'Tinder Android Version 2.2.3',
        os_version: '16' },
     method: 'get',
     baseURL: 'https://api.gotinder.com',
     url: 'https://api.gotinder.com/pass/5c5c55b5e36e5f1100456d97',
     data: undefined },
  request:
   ClientRequest {
     _events:
      [Object: null prototype] {
        socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'api.gotinder.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'api.gotinder.com',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 60,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'api.gotinder.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'api.gotinder.com',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 60,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     _header:
      'GET /pass/5c5c55b5e36e5f1100456d97 HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nX-Auth-Token: .........\r\nContent-Type: application/json\r\nUser-Agent: Tinder Android Version 2.2.3\r\nos_version: 16\r\nHost: api.gotinder.com\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     path: '/pass/5c5c55b5e36e5f1100456d97',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [TLSSocket],
        connection: [TLSSocket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 400,
        statusMessage: 'Bad Request',
        client: [TLSSocket],
        _consuming: false,
        _dumped: false,
        req: [Circular],
        responseUrl: 'https://api.gotinder.com/pass/5c5c55b5e36e5f1100456d97',
        redirects: [] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [WritableState],
        writable: true,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _ended: true,
        _ending: true,
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 0,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl: 'https://api.gotinder.com/pass/5c5c55b5e36e5f1100456d97' },
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]:
      [Object: null prototype] {
        accept: [Array],
        'x-auth-token': [Array],
        'content-type': [Array],
        'user-agent': [Array],
        os_version: [Array],
        host: [Array] } },
  response:
   { status: 400,
     statusText: 'Bad Request',
     headers:
      { 'content-type': 'application/json; charset=utf-8',
        date: 'Thu, 07 Feb 2019 17:56:17 GMT',
        'x-request-id': '.................',
        'content-length': '42',
        connection: 'Close' },
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'get',
        baseURL: 'https://api.gotinder.com',
        url: 'https://api.gotinder.com/pass/5c5c55b5e36e5f1100456d97',
        data: undefined },
     request:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header:
         'GET /pass/5c5c55b5e36e5f1100456d97 HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nX-Auth-Token: .................\r\nContent-Type: application/json\r\nUser-Agent: Tinder Android Version 2.2.3\r\nos_version: 16\r\nHost: api.gotinder.com\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/pass/5c5c55b5e36e5f1100456d97',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     data: { status: 400, error: 'malformed request' } } }
```

**Comment by jaebradley** [comment]
@RikuHirose thanks for opening this issue!

I'll try and take a look at this in the next 48 hours.

In the meantime, I'd suggest cleaning up any personal information in the issue details (there is some FB auth token information, for example).

**Comment by Cyb3rFl3x** [comment]
I got the same issue...

**Comment by jaebradley** [comment]
@RikuHirose and @Frontstriker15 this is caused by [the `Content-Type: application/json` header](https://github.com/jaebradley/tinder-client/blob/master/src/index.js#L36).

It's a `GET` request with a non-existent payload and so the server rejects the request.

My plan is to have a fix published to `npm` within 24 hours.
